from __future__ import annotations

from typing import Any


DEPRECATED_TASK_IDS = (
    "build_cold_universe",
    "cold_company_profile_batch_0",
    "warm_hard_evidence_auto",
)


SCHEDULED_TASKS: list[dict[str, Any]] = [
    {
        "task_id": "cold_company_profile",
        "task_name": "冷数据：公司画像",
        "task_description": "初始化或按需补全公司画像；默认不自动执行。",
        "task_kind": "cold_company_profile",
        "task_type": "cold",
        "enabled": 0,
        "schedule_type": "manual",
        "interval": 315360000,
        "priority": 80,
        "timeout": 1800,
        "payload": {"batch_size": 100, "cache_only": False, "workers": 4},
        "dedupe": "cold_company_profile:{run_key}:{offset}",
    },
    {
        "task_id": "ths_root_extended_items",
        "task_name": "根页面扩展信息",
        "task_description": "每晚全量刷新同花顺根页面近期事件、公告、题材要点。",
        "task_kind": "ths_root_extended_items",
        "task_type": "cold",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 70,
        "timeout": 1800,
        "payload": {"batch_size": 100, "cache_only": False, "workers": 4, "request_timeout": 8, "max_pages": 1},
        "dedupe": "ths_root_extended_items:{run_key}:{offset}",
    },
    {
        "task_id": "morning_market_news",
        "task_name": "早盘资讯：财联社/华尔街见闻",
        "task_description": "每天8:30抓取财联社和华尔街见闻头条、昨日盘后至今的重要快讯。",
        "task_kind": "morning_market_news",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 50,
        "timeout": 300,
        "payload": {"important_only": True, "limit": 80, "limit_per_source": 50, "after_close_hour": 15, "timeout": 10},
        "dedupe": "morning_market_news:{run_key}",
    },
    {
        "task_id": "daily_market_themes",
        "task_name": "早盘主题雷达",
        "task_description": "每天8:32把早盘资讯加工成今日催化主题池。",
        "task_kind": "daily_market_themes",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 55,
        "timeout": 180,
        "payload": {"min_importance": 2, "limit_titles": 5, "after_close_hour": 15},
        "dedupe": "daily_market_themes:{run_key}",
    },
    {
        "task_id": "morning_reference_post",
        "task_name": "早参帖子",
        "task_description": "每天8:35基于上一个交易日收盘后至今的盘前消息，用模型总结生成早参帖子。",
        "task_kind": "morning_reference_post",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 56,
        "timeout": 180,
        "payload": {
            "min_importance": 2,
            "theme_limit": 8,
            "news_limit": 30,
            "after_close_hour": 15,
            "model_config": "default",
            "model_timeout": 60,
            "fallback_without_model": True,
        },
        "dedupe": "morning_reference_post:{run_key}",
    },
    {
        "task_id": "ths_hot_concepts",
        "task_name": "低频数据：同花顺今天炒什么",
        "task_description": "每天收盘后更新一次同花顺今天炒什么事件、主题成分股，并重建近14日有效锚点池。",
        "task_kind": "ths_hot_concepts",
        "task_type": "cold",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 65,
        "timeout": 900,
        "payload": {"days": 14, "max_pages": 8, "timeout": 15, "pause": 0.15},
        "dedupe": "ths_hot_concepts:{run_key}",
    },
    {
        "task_id": "ths_limit_up_review",
        "task_name": "THS Limit-Up Review",
        "task_description": "Collect THS limit-up review attribution and rebuild recent limit-up theme anchors.",
        "task_kind": "ths_limit_up_review",
        "task_type": "cold",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 67,
        "timeout": 900,
        "payload": {"days": 1, "timeout": 12, "pause": 0.2, "lookback_days": 14},
        "dedupe": "ths_limit_up_review:{run_key}",
    },
    {
        "task_id": "ths_stock_concepts",
        "task_name": "THS Stock Concept Explanations",
        "task_description": "Collect THS per-stock concept explanations from F10 concept page.",
        "task_kind": "ths_stock_concepts",
        "task_type": "cold",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 64,
        "timeout": 900,
        "payload": {"batch_size": 200, "timeout": 10, "pause": 0.08, "chunk_size": 300},
        "dedupe": "ths_stock_concepts:{run_key}:{offset}",
    },
    {
        "task_id": "stock_theme_reason_bank",
        "task_name": "Stock Theme Reason Bank",
        "task_description": "Rebuild global stock-theme reason bank from THS hot concepts, stock concept explanations, and fallback tags.",
        "task_kind": "stock_theme_reason_bank",
        "task_type": "cold",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 66,
        "timeout": 900,
        "payload": {"include_stock_concepts": True, "include_concept_tags": False, "chunk_size": 500},
        "dedupe": "stock_theme_reason_bank:{run_key}",
    },
    {
        "task_id": "iwencai_period_rankings",
        "task_name": "iWenCai Period Rankings",
        "task_description": "Collect iWenCai 3/5/10-day gain rankings for anchor leadership scoring.",
        "task_kind": "iwencai_period_rankings",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 45,
        "timeout": 180,
        "payload": {"periods": "3,5,10", "top": 50, "universe": "沪深A股"},
        "dedupe": "iwencai_period_rankings:{run_key}",
    },
    {
        "task_id": "lhb_seat_evidence",
        "task_name": "LHB Seat Evidence",
        "task_description": "Collect useful Dragon-Tiger list seat structure: famous active traders, institutions, northbound, and top buy seats.",
        "task_kind": "lhb_seat_evidence",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 46,
        "timeout": 300,
        "payload": {"limit": 120, "judgement_codes": True},
        "dedupe": "lhb_seat_evidence:{run_key}",
    },
    {
        "task_id": "announcement_effects",
        "task_name": "Announcement Effects",
        "task_description": "Build market-validated announcement and important-event effects from stock_ths_root_items.",
        "task_kind": "announcement_effects",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 47,
        "timeout": 900,
        "payload": {
            "lookback_days": 240,
            "stale_after_days": 31,
            "sleep_seconds": 0.15,
            "refresh_bars": True,
            "allow_local_fallback": False,
        },
        "dedupe": "announcement_effects:{run_key}",
    },
    {
        "task_id": "effective_facts",
        "task_name": "Effective Facts",
        "task_description": "Build filtered effective fact layer for evidence cache, UI, and model payloads.",
        "task_kind": "effective_facts",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 48,
        "timeout": 300,
        "payload": {},
        "dedupe": "effective_facts:{run_key}",
    },
    {
        "task_id": "async_evidence_source_sync",
        "task_name": "Async Evidence Source Sync",
        "task_description": "Refresh per-stock evidence fingerprints and enqueue only changed stocks for model analysis.",
        "task_kind": "async_evidence_source_sync",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 60,
        "priority": 46,
        "timeout": 120,
        "payload": {"limit": 50, "per_kind_limit": 8, "model_config": "default", "timeout": 30, "fallback_without_model": True},
        "dedupe": "async_evidence_source_sync:{minute_key}",
    },
    {
        "task_id": "root_evidence_cache_dirty",
        "task_name": "Root Evidence Cache Dirty",
        "task_description": "Consume changed stock root evidence rows and refresh affected stock cache only.",
        "task_kind": "root_evidence_cache_dirty",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 30,
        "priority": 45,
        "timeout": 120,
        "payload": {"limit": 50},
        "dedupe": "root_evidence_cache_dirty:{minute_key}",
    },
    {
        "task_id": "event_engine",
        "task_name": "Event Evidence Engine",
        "task_description": "Build normalized move events, derived signals, and event-level evidence.",
        "task_kind": "event_engine",
        "task_type": "hot",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 60,
        "priority": 44,
        "timeout": 120,
        "payload": {"limit": 800},
        "dedupe": "event_engine:{minute_key}",
    },
    {
        "task_id": "async_evidence_summary",
        "task_name": "Async Evidence Summary",
        "task_description": "Consume pending changed evidence rows and summarize them with model analysis.",
        "task_kind": "async_evidence_summary",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 300,
        "priority": 48,
        "timeout": 300,
        "payload": {"limit": 10, "per_kind_limit": 8, "model_config": "default", "timeout": 60, "dirty_only": True, "fallback_without_model": True},
        "dedupe": "async_evidence_summary:{minute_key}",
    },
    {
        "task_id": "stock_move_judgements",
        "task_name": "Stock Move Judgements",
        "task_description": "Build concise move explanation and sustainability judgement from tape, anchor, role, and async evidence.",
        "task_kind": "stock_move_judgements",
        "task_type": "hot",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 60,
        "priority": 49,
        "timeout": 120,
        "payload": {"scan_top": 20, "window_top": 5, "limit": 500, "latest_only": True},
        "dedupe": "stock_move_judgements:{minute_key}",
    },
    {
        "task_id": "stock_move_judgement_dirty",
        "task_name": "Stock Move Judgement Dirty",
        "task_description": "Consume changed evidence rows and rebuild affected move judgements.",
        "task_kind": "stock_move_judgements",
        "task_type": "hot",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 60,
        "priority": 50,
        "timeout": 120,
        "payload": {"scan_top": 20, "window_top": 5, "limit": 80, "latest_only": False, "dirty_only": True},
        "dedupe": "stock_move_judgement_dirty:{minute_key}",
    },
    {
        "task_id": "anchor_realtime_roles",
        "task_name": "热数据：题材锚点全池角色",
        "task_description": "交易时段按题材锚点股票池计算全池领涨/中军，供实时扫描和Web展示引用。",
        "task_kind": "anchor_realtime_roles",
        "task_type": "hot",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 60,
        "priority": 35,
        "timeout": 90,
        "payload": {"levels": "strong,medium", "medium_cap": 120, "min_members": 2, "batch_size": 80, "tdx_timeout": 3, "trading_only": True},
        "dedupe": "anchor_realtime_roles:{minute_key}",
    },
    {
        "task_id": "auction_candidates",
        "task_name": "09:25竞价候选池",
        "task_description": "09:25按高开幅度、竞价金额、今日主题命中、板块共振生成开盘前候选池。",
        "task_kind": "auction_candidates",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 58,
        "timeout": 540,
        "payload": {
            "limit": 50,
            "min_auction_pct": 1.0,
            "min_auction_amount": 10000000,
            "theme_limit": 20,
            "timeout": 3,
            "batch_size": 80,
            "minute_analysis": True,
            "loop_until": "09:25",
            "minute_interval": 60,
            "minute_top": 10,
            "seal_top": 10,
        },
        "dedupe": "auction_candidates:{run_key}",
    },
    {
        "task_id": "auction_trend_summary",
        "task_name": "09:26 auction trend summary",
        "task_description": "Compress 09:20-09:25 auction minute radar into per-stock trend score, label, key points, and action hint.",
        "task_kind": "auction_trend_summary",
        "task_type": "warm",
        "enabled": 1,
        "schedule_type": "interval",
        "interval": 86400,
        "priority": 59,
        "timeout": 180,
        "payload": {"limit": 80},
        "dedupe": "auction_trend_summary:{run_key}",
    },
]


NEXT_RUN_SQL_BY_TASK = {
    "ths_root_extended_items": "IF(TIME(NOW()) < '22:00:00', TIMESTAMP(CURDATE(), '22:00:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '22:00:00'))",
    "morning_market_news": "IF(TIME(NOW()) < '08:30:00', TIMESTAMP(CURDATE(), '08:30:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '08:30:00'))",
    "daily_market_themes": "IF(TIME(NOW()) < '08:32:00', TIMESTAMP(CURDATE(), '08:32:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '08:32:00'))",
    "morning_reference_post": "IF(TIME(NOW()) < '08:35:00', TIMESTAMP(CURDATE(), '08:35:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '08:35:00'))",
    "ths_hot_concepts": "IF(TIME(NOW()) < '15:30:00', TIMESTAMP(CURDATE(), '15:30:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '15:30:00'))",
    "ths_limit_up_review": "IF(TIME(NOW()) < '15:40:00', TIMESTAMP(CURDATE(), '15:40:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '15:40:00'))",
    "ths_stock_concepts": "IF(TIME(NOW()) < '15:35:00', TIMESTAMP(CURDATE(), '15:35:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '15:35:00'))",
    "stock_theme_reason_bank": "IF(TIME(NOW()) < '16:20:00', TIMESTAMP(CURDATE(), '16:20:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '16:20:00'))",
    "iwencai_period_rankings": "IF(TIME(NOW()) < '15:20:00', TIMESTAMP(CURDATE(), '15:20:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '15:20:00'))",
    "lhb_seat_evidence": "IF(TIME(NOW()) < '15:35:00', TIMESTAMP(CURDATE(), '15:35:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '15:35:00'))",
    "announcement_effects": "IF(TIME(NOW()) < '22:45:00', TIMESTAMP(CURDATE(), '22:45:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '22:45:00'))",
    "async_evidence_source_sync": "IF(TIME(NOW()) < '09:35:00', TIMESTAMP(CURDATE(), '09:35:00'), NOW(3))",
    "root_evidence_cache_dirty": "IF(TIME(NOW()) < '09:35:00', TIMESTAMP(CURDATE(), '09:35:00'), NOW(3))",
    "event_engine": "IF(TIME(NOW()) < '09:35:00', TIMESTAMP(CURDATE(), '09:35:00'), NOW(3))",
    "async_evidence_summary": "IF(TIME(NOW()) < '09:35:00', TIMESTAMP(CURDATE(), '09:35:00'), NOW(3))",
    "stock_move_judgements": "IF(TIME(NOW()) < '09:35:00', TIMESTAMP(CURDATE(), '09:35:00'), NOW(3))",
    "stock_move_judgement_dirty": "IF(TIME(NOW()) < '09:35:00', TIMESTAMP(CURDATE(), '09:35:00'), NOW(3))",
    "auction_candidates": "IF(TIME(NOW()) < '09:20:00', TIMESTAMP(CURDATE(), '09:20:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '09:20:00'))",
    "auction_trend_summary": "IF(TIME(NOW()) < '09:26:00', TIMESTAMP(CURDATE(), '09:26:00'), TIMESTAMP(DATE_ADD(CURDATE(), INTERVAL 1 DAY), '09:26:00'))",
}


def next_run_sql_for_task(task_id: str) -> str:
    return NEXT_RUN_SQL_BY_TASK.get(task_id, "NULL")
